// <auto-generated />
using Book_Management_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Book_Management_Api.Migrations
{
    [DbContext(typeof(BookDetailContext))]
    [Migration("20220104101745_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Book_Management_Api.Models.BookDetail", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("BookId");

                    b.ToTable("BookDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
